<?php

define('AUTORELOAD_FILE', 'changed');

/**
 * Implementation of hook_init().
 */
function autoreload_init() {
  $settings = array(
    'autoreload' => array(
      'file' => autoreload_changed_file(FALSE),
    ),
  );
  drupal_add_js($settings, 'setting');
  drupal_add_js(drupal_get_path('module', 'autoreload') .'/autoreload.js');
}

/**
 * Implementation of function hook_feeds_after_import().
 */
function autoreload_feeds_after_import(FeedsImporter $importer, FeedsSource $source) {
  $h = fopen(autoreload_changed_file(TRUE), 'w');
  fwrite($h, FEEDS_REQUEST_TIME);
  fclose($h);
}

/**
 * Return the path to the autoreload changed file, may or may not exist.
 */
function autoreload_changed_file($absolute) {
  if ($absolute) {
    return realpath(file_directory_path()) .'/'. AUTORELOAD_FILE;
  }
  return file_directory_path() .'/'. AUTORELOAD_FILE;
}
